### ISSUE TITLE
在docker容器中如何编译该项目？

### ISSUE THREAD

**Issue by GaoXiangYa** [piood/MySysY2RV#1]
使用make编译的时候，报错：/usr/bin/ld: cannot find -lkoopa: No such file or directory

**Comment by piood** [comment]
> 使用make编译的时候，报错：/usr/bin/ld: cannot find -lkoopa: No such file or directory

文档已经更新，环境配置请看https://pku-minic.github.io/online-doc/#/lv0-env-config/docker,
本项目是北大编译课程https://pku-minic.github.io/online-doc/#/ 的项目实践。
